copy template

diff --git a/.github/workflows/trivy.yml b/.github/workflows/trivy.yml
--- a/.github/workflows/trivy.yml
+++ b/.github/workflows/trivy.yml
@@ -1,5 +1,3 @@
-
-
 name: "Trivy Scans"
 
 on:
@@ -33,14 +31,36 @@ jobs:
           git config --global --add safe.directory $GITHUB_WORKSPACE;
           docker build -t trivy-test .
 
-      - name: Run Trivy vulnerability scanner
-        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
+      - name: Run Trivy vulnerability scanner, output as table
+        uses: aquasecurity/trivy-action@master
         with:
-          image-ref: 'trivy-test'
-          format: 'template'
-          template: '@/contrib/sarif.tpl'
-          output: 'trivy-results.sarif'
-          severity: 'CRITICAL,HIGH'
+          image-ref: "trivy-test"
+          format: "table"
+          output: "trivy-results.tbl"
+          timeout: "20m0s"
+
+      - name: Check for log4j CVEs
+        run: |
+          set -e
+          for cve in CVE-2021-4104 CVE-2021-44228 CVE-2021-45046 CVE-2022-22965 ; do
+            if grep -c $cve trivy-results.tbl > 0;
+              then
+                echo "Found log4j error: $cve"
+                exit 2
+            fi
+          done
+          # If above doesn't find errors, return pass message:
+          echo "Did not find core log4j errors, yay!"
+
+      - name: Rerun Trivy vulnerability scanner for GitHub security
+        uses: aquasecurity/trivy-action@master
+        if: always()
+        with:
+          image-ref: "trivy-test"
+          format: "sarif"
+          output: "trivy-results.sarif"
+          timeout: "20m0s"
+          ignore-unfixed: true
 
       - name: Upload Trivy scan results to GitHub Security tab
         uses: github/codeql-action/upload-sarif@v3
